### ISSUE TITLE
Improvement in the UI of content of the dropdown "Weird things of Javascript"

### ISSUE THREAD

**Issue by TUSHAR-30** [TUSHAR-30/Javascript-Output-Based-Question#1]
We can improve its UI by adding more space between dropdown heading and its content.
The content of dropdown of "Weird things of Javascript" is having less spacing with its dropdown heading.And due to this UI is not looking good.

![temp](https://github.com/user-attachments/assets/33af7b93-bf5b-440c-9565-a556d697b278)

**Comment by Coding-with-Tushar** [comment]
I want to solve this issue
